import os
import glob
import cv2
import numpy as np

def batch_measure_pothole_areas(input_folder, output_folder, road_lane_width_mm=3500, out_w=1000):
    """
    Scans a folder for processed bird's-eye view images, isolates potholes,
    calculates their surface area, and saves visual inspection overlays.
    
    CRITICAL FIXES APPLIED:
    1. Blinds the detector to the top-left metadata banner area to prevent false text detections.
    2. Retunes the adaptive threshold sensitivity to capture smoother asphalt depressions.
    """
    # Ensure output directory exists
    os.makedirs(output_folder, exist_ok=True)

    # Find all images processed by the transformation step
    valid_extensions = ('*.jpg', '*.jpeg', '*.png', '*.JPG', '*.JPEG', '*.PNG')
    image_paths = []
    for ext in valid_extensions:
        image_paths.extend(glob.glob(os.path.join(input_folder, ext)))

    # Filter to only run on files generated by your main pipeline
    processed_images = [p for p in image_paths if os.path.basename(p).startswith("processed_")]

    if not processed_images:
        print(f"No files starting with 'processed_' found in: {input_folder}")
        return

    print(f"Beginning Batch Area Measurements for {len(processed_images)} images...\n")

    # Establish Ground Sample Distance (GSD) metric scaling constants
    pixel_scale_mm = road_lane_width_mm / out_w
    sq_mm_per_pixel = pixel_scale_mm ** 2

    # Loop through every image file found in the directory
    for path in processed_images:
        base_name = os.path.basename(path)
        img = cv2.imread(path)
        if img is None:
            print(f"[{base_name}] Skipped: Unable to parse image matrix.")
            continue

        # --- FIX 1: BANNER ZONE EXCLUSION MASK ---
        # The watermark banner sits at the top-left (width: 420, height: 220).
        # We build a blank mask of the same image dimensions and fill the banner region with black (0).
        analysis_mask = np.ones(img.shape[:2], dtype=np.uint8) * 255
        cv2.rectangle(analysis_mask, (0, 0), (430, 230), 0, -1)  # Painted black with a slight safety buffer

        # --- CONTRAST FILTERING & SEGMENTATION ---
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        blurred = cv2.GaussianBlur(gray, (7, 7), 0)
        
        # --- FIX 2: ADJUSTED THRESHOLD SENSITIVITY ---
        # Changed the subtraction constant 'C' from 12 to 7. 
        # This makes it substantially more sensitive to the smooth, gradual gradients of real potholes.
        thresh = cv2.adaptiveThreshold(
            blurred, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, 
            cv2.THRESH_BINARY_INV, 15, 7
        )

        # Apply our exclusion mask to the binary threshold matrix
        thresh = cv2.bitwise_and(thresh, thresh, mask=analysis_mask)

        # Find the contours (shapes) of the remaining isolated dark regions
        contours, _ = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        
        total_potholes_in_frame = 0
        output_visual = img.copy()

        # Check every detected contour shape inside this frame
        for contour in contours:
            pixel_area = cv2.contourArea(contour)
            
            # QC Filter: Slightly lowered noise cutoff to 350 pixels to avoid missing tighter failures
            if pixel_area < 350:
                continue
                
            total_potholes_in_frame += 1

            # Convert pixel area measurements into real-world units
            area_mm2 = pixel_area * sq_mm_per_pixel
            area_m2 = area_mm2 / 1_000_000.0

            # Generate bounding box markers for visual confirmation overlays
            x, y, w, h = cv2.boundingRect(contour)
            cv2.rectangle(output_visual, (x, y), (x + w, y + h), (0, 0, 255), 2)
            
            label = f"ID:{total_potholes_in_frame} {area_m2:.3f} m2"
            cv2.putText(output_visual, label, (x, y - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 2)

        # Write data to console telemetry log
        print(f"[{base_name}] Identified: {total_potholes_in_frame} structural defects.")

        # Save out the finished file labeled as measured_
        output_name = base_name.replace("processed_", "measured_")
        output_path = os.path.join(output_folder, output_name)
        cv2.imwrite(output_path, output_visual)

    print("\n--- Folder processing completely finished! ---")


if __name__ == "__main__":
    # Point this to where your warped, watermarked outputs are stored
    PROCESSED_DIR = r"C:\OPTIK\ExtractEXIF\Processed_Outputs"
    
    # Folder destination where the marked measurement images will go
    MEASURED_DIR = r"C:\OPTIK\ExtractEXIF\Measured_Outputs"

    # Calibration settings matching global setup (OUT_W = 1000, Lane = 3.5m)
    batch_measure_pothole_areas(PROCESSED_DIR, MEASURED_DIR, road_lane_width_mm=3500, out_w=1000)